Pull Request from feat/change password
GroupeNRM/Youngfood pull request #24
Opened 2020-05-15 21:25 UTC by SmashScharrer

Create & Config new feature : Request & Reset Password Method

2020-05-15 21:32 UTC, Kayoshi-dev requested changes

2020-05-15 21:32 UTC, Kayoshi-dev commented on src/Form/ChangePasswordFormType.php
> +                        new NotBlank([
Afficher en français

2020-05-15 21:32 UTC, Kayoshi-dev commented on src/Form/ResetPasswordRequestFormType.php
> +                        'message' => 'Please enter your email',
Message en français

2020-05-15 21:32 UTC, Kayoshi-dev commented on templates/reset_password/email.html.twig
> +<p>
Traduire fr

2020-05-15 21:32 UTC, Kayoshi-dev commented on assets/scss/request.scss
> +@import "variables";
propriétés déjà existantes dans login.scss, les déplacer dans _form.scss si nécéssaire

2020-05-16 13:19 UTC, SmashScharrer commented
J'ai fais les quelques changements. Y a-t-il autres choses à corriger ?

2020-05-17 22:52 UTC, Kayoshi-dev approved these changes
lets gooooooooooooo, normalement tout marche

2020-05-17 22:59 UTC, merged