Pull Request feat/user-crud Branch
GroupeNRM/Youngfood pull request #42
Opened 2020-05-26 23:10 UTC by SmashScharrer

Create New User CRUD

2020-05-26 23:16 UTC, Kayoshi-dev requested changes
qq trads a faire, et ajouter le js des notifs

2020-05-26 23:16 UTC, Kayoshi-dev commented on src/Form/UserType.php
> +                    'H' => 'H',
homme / femme plutot que H/F

2020-05-26 23:16 UTC, Kayoshi-dev commented on templates/admin/user/_delete_form.html.twig
> +<form method="post" action="{{ path('admin.supprimerUtilisateur', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
traduire en fr

2020-05-26 23:16 UTC, Kayoshi-dev commented on templates/admin/user/index.html.twig
> +                    <td colspan="9">No records found</td>
traduire fr

2020-05-26 23:16 UTC, Kayoshi-dev commented on templates/admin/user/index.html.twig
> +{% block javascripts %}
ajouter {{ encore_entry_script_tags('notification') }}

2020-05-26 23:16 UTC, Kayoshi-dev commented on templates/admin/user/show.html.twig
> +{% block javascripts %}
ajouter {{ encore_entry_script_tags('notification') }}

2020-05-26 23:22 UTC, SmashScharrer commented on templates/admin/user/index.html.twig
> +{% block javascripts %}
on devrait pas le rajouter sur le template de base ?

2020-05-27 10:26 UTC, Kayoshi-dev approved these changes
good

2020-05-27 10:27 UTC, merged